name: Build codex Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/codex

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: lowercase-repo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Checkout codex
        uses: actions/checkout@v4
        with:
          repository: openai/codex

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          provenance: false
          platforms: "linux/arm64,linux/amd64"
          context: "{{defaultContext}}:codex/codex-cli"
          #context: https://github.com/openai/codex.git:codex-cli
          #file: codex-cli/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.lowercase-repo.outputs.lowercase }}:latest
