name: Build ktools-test Image

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ktools-test/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/ktools-test

jobs:
  ubuntu:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # provenance: false
          platforms: ${{ matrix.platform }}
          context: ktools-test
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  # mac:
  #   permissions:
  #     contents: read
  #     packages: write
  #   runs-on: macos-latest
  #   steps:
  #     - name: Install deps
  #       run: |
  #         brew update
  #         brew install docker
  #         brew install colima
  #         sudo curl -L -o /opt/homebrew/Cellar/lima/0.22.0/bin/limactl https://github.com/mikekazakov/lima-nohvf/raw/master/limactl && sudo chmod +x /opt/homebrew/Cellar/lima/0.22.0/bin/limactl
  #         colima start --network-address --arch arm64 --vm-type=qemu
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Log in to the Container registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         # provenance: false
  #         platforms: ${{ matrix.platform }}
  #         context: ktools-test
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
