name: Build simple-block-explorer Image

on:
  workflow_dispatch:
    inputs:
        MAIN_ENDPOINT_PROTOCOL:
            description: http or https
            default: http
            type: string
        MAIN_ENDPOINT_HOST:
            description: 127.0.0.1
            default: 127.0.0.1
            type: string
        MAIN_ENDPOINT_PORT:
            description: '8332'
            default: '8332'
            type: string
        TEST_ENDPOINT_PROTOCOL:
            description: http or https
            default: http
            type: string
        TEST_ENDPOINT_HOST:
            description: 127.0.0.1
            default: 127.0.0.1
            type: string
        TEST_ENDPOINT_PORT:
            description: '18332'
            default: '18332'
            type: string

#  push:
#    branches:
#      - main
#    paths:
#      - simple-block-explorer/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/simple-block-explorer

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          provenance: false
          platforms: "linux/arm64,linux/amd64"
          context: simple-block-explorer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
