name: Build Test Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/test

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            runner: ubuntu-24.04
          - arch: arm64
            platform: linux/arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: lowercase-repo
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          provenance: false
          platforms: ${{ matrix.platform }} # Hier hat man das Problem, dass die Images getrennt voneinander hochgeladen werden und nur eines den Tag 'latest' bekommt, nur ein Image von einer Architektur. Bei einem Pull bekommt man also nicht automatisch das richtige Image für seine Architektur.
          context: https://github.com/RCasatta/fbbe.git
          file: docker/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.lowercase-repo.outputs.lowercase }}:latest
